abu="\e[1;90m"
red="\e[1;91m"
green="\e[1;92m"
yellow="\e[1;93m"
blue="\e[1;94m"
purple="\e[1;95m"
cyan="\e[1;96m"
b_abu="\e[1;100m"
b_black="\e[1;40m"
b_red="\e[1;41m"
b_green="\e[1;42m"
b_brown="\e[1;43m"
b_blue="\e[1;44m"
b_purple="\e[1;45m"
b_cyan="\e[1;46m"
b_white="\e[1;7m"
underscore="\e[1;4m"
italic="\e[1;3m"
klap_klip="\e[1;5m"
normal="\e[1;0m"
printf "${klap_klip}${purple} KRYPTON WEB SHELL\n${normal}"
printf "${yellow}Pentest\t\t Language\n"
printf "\t${cyan}SQMLAP\t\t Python\n"
printf "\t${cyan}WPSCAN\t\t NodeJs\n"
printf "\t${cyan}JOOMSCAN\t PHP\n"
printf "\t${cyan}NMAP\t\t Perl\n"
printf "\t${cyan}WHATWEB\t\t Ruby\n${normal}"